version: '2'

services: 
    app: 
        build: 
            context: .
        restart: always
        ports:
            - "3000:3000"
        container_name: app
        volumes:
            - ./src/:/app/src/
